### ISSUE TITLE
Facing problems with plugin on migration to public server

### ISSUE THREAD

**Issue by NMorgana** [rainlab/builder-plugin#194] opened 2017-10-27 18:32 UTC
After installing Octobercms on the public server and updating the related plugins (builder included), I've moved the custom plugins that has been generated by the builder plugin on my local server, manually to the plugins directory on the public server, followed up with the command line of "october:up". I'm now receiving the following errors, while trying to access the builder plugin on the back-end. I've tried re-installing the builder plugin, but the problem keeps producing. I'm quite new to the framework of October Cms and Laravel, any advice/assistance I can receive is really appreciated. Thank you.

Call to undefined method RainLab\Builder\Widgets\ModelList::getCollapseStatus()
/home/morgan51/dev.morgana-design.com/vendor/october/rain/src/Extension/ExtendableTrait.php line 388
```
    Type:  Undefined
    Exception:   BadMethodCallException

$parent = get_parent_class();
        if ($parent !== false && method_exists($parent, '__call')) {
            return parent::__call($name, $params);
        }
  
        throw new BadMethodCallException(sprintf(
            'Call to undefined method %s::%s()',
            get_class($this),
            $name
        ));
    }
Call to undefined method RainLab\Builder\Widgets\ModelList::getCollapseStatus()
/home/morgan51/dev.morgana-design.com/vendor/october/rain/src/Extension/ExtendableTrait.php line 388

    Type
    Undefined

    Exception
    BadMethodCallException

$parent = get_parent_class();
        if ($parent !== false && method_exists($parent, '__call')) {
            return parent::__call($name, $params);
        }
  
        throw new BadMethodCallException(sprintf(
            'Call to undefined method %s::%s()',
            get_class($this),
            $name
        ));
    }

```

**Comment by LukeTowers** [comment] 2017-10-27 19:07
Duplicate of #193

**Comment by LukeTowers** [comment] 2017-10-27 19:08
@NMorgana to fix it, enable edgeUpdates in config/cms.php and then update again.

**Closed by LukeTowers** 2017-10-27 19:07 UTC

**Comment by NMorgana** [comment] 2017-10-29 19:23
Thank you, that fixed the issue!
