### ISSUE TITLE
Model title in breadcrumb and other files is not translatable by default

### ISSUE THREAD

**Issue by Hambern** [rainlab/builder-plugin#111] opened 2016-09-15 18:15 UTC
The title of the model is not translatable by default in the breadcrumbs in the controllers generated by the Builder plugin. The generated breadcrumb code looks like this:

~~~php
<?php Block::put('breadcrumb') ?>
    <ul>
        <li><a href="<?= Backend::url('my/plugin/things') ?>">Things</a></li>
        <li><?= e($this->pageTitle) ?></li>
    </ul>
<?php Block::endPut() ?>
~~~

As you can see the word "Things" is not translatable by default. To fix this we should do:

~~~php
<?php Block::put('breadcrumb') ?>
    <ul>
        <li>
            <a href="<?= Backend::url('my/plugin/things') ?>">
                <?= e(trans('my.plugin::lang.plugin.things')) ?>
            </a>
        </li>
        <li><?= e($this->pageTitle) ?></li>
    </ul>
<?php Block::endPut() ?>
~~~

...Or something like that. You can call and place the translation wherever really. This concerns the following files:
- `/plugins/my/plugin/controllers/things/create.htm`
- `/plugins/my/plugin/controllers/things/preview.htm`
- `/plugins/my/plugin/controllers/things/reorder.htm`
- `/plugins/my/plugin/controllers/things/update.htm`

Finally... this seems to also be the case in the "name" and "title" fields in the following files:
- `/plugins/my/plugin/controllers/things/config_form.yaml`
- `/plugins/my/plugin/controllers/things/config_list.yaml`
- `/plugins/my/plugin/controllers/things/config_reorder.yaml`

Could someone please fix this? ;)

**Comment by daftspunk** [comment] 2016-09-18 07:50
This appears to be a duplicate of the comment made in #29. Builder produces basic scaffold, it is up to you to translate the files. Look at any of the RainLab plugins for an example.

https://github.com/rainlab/

**Closed by daftspunk** 2016-09-18 07:50 UTC
