### ISSUE TITLE
Call to undefined method RainLab\Builder\Widgets\ModelList::getCollapseStatus() 419

### ISSUE THREAD

**Issue by devalexandre** [rainlab/builder-plugin#195] opened 2017-11-02 13:25 UTC
Expected behavior

create a model for my plugin

Actual behavior

Error in method of plugin

BadMethodCallException: Call to undefined method RainLab\Builder\Widgets\ModelList::getCollapseStatus() in /srv/http/octobercms/vendor/october/rain/src/Extension/ExtendableTrait.php:388

Reproduce steps

Install RainLab Builder plugin
Create a plugin name Featured
create database tabel indev_featured
fields
id integer primary key
name string 100
content text
image text

after I try create a model, here is error

October build

419

I try update using 'edgeUpdates' => true, and run in comand line
php artisan october:update
but don't have updates

**Comment by LukeTowers** [comment] 2017-11-02 14:15
Duplicate of #193. Try updating through the web interface instead. Also, make sure disableCoreUpdates is set to false. Alternatively, switch your composer.json to pull from the dev branch directly if you are using composer.

**Closed by LukeTowers** 2017-11-02 14:15 UTC
