### ISSUE TITLE
Backend Menu throwing Javascript Errors, won't load

### ISSUE THREAD

**Issue by cjoh** [rainlab/builder-plugin#34] opened 2016-02-16 17:53 UTC
Created a table 
![0216jijob](https://cloud.githubusercontent.com/assets/8958/13085339/c1071894-d4ab-11e5-8a9c-9336fae557f3.png)

Saved it.

Clicking "permissions" or "Backend Menu" causes the blue progress meter to load infinitely, and to throw a javascript error:

![0216x2t4h](https://cloud.githubusercontent.com/assets/8958/13085397/21ab2f0a-d4ac-11e5-83de-adc90953a978.png)

![0216u9htf](https://cloud.githubusercontent.com/assets/8958/13085409/316a317a-d4ac-11e5-8b4c-42475637f7ca.png)

**Comment by alekseybobkov** [comment] 2016-02-17 00:53
I can't reproduce the problem. But I assume it could happen if there was a server error. Can you check the AJAX requests and see if there are any errors in the responses?

**Comment by alekseybobkov** [comment] 2016-03-03 05:26
Closing as it wasn't confirmed for two weeks. Please reopen and submit more information if the problem still exists.

**Closed by alekseybobkov** 2016-03-03 05:26 UTC
Labels: unconfirmed bug
