### ISSUE TITLE
Hangup after error

### ISSUE THREAD

**Issue by ovillani** [rainlab/builder-plugin#283] opened 2019-05-27 10:54 UTC
By creating a table and marking false combinations of PK, unsigned builder informs about the error correctly but hangs afterwards-

**Comment by bennothommo** [comment] 2019-05-28 04:47
@ovillani Would you be able to provide us a screenshot of what you entered into the table editor and the error message you received afterwards, so we can try and replicate the issue?

**Comment by ovillani** [comment] 2019-06-02 18:34
@bennothommo Hi, here are some screenshots as an example:
1. Set up a table with some columns with non-matching properties like this
![Clipboard01](https://user-images.githubusercontent.com/6983432/58765629-4a8e0500-8575-11e9-8992-ca4976c22f9b.jpg)

2. (Try to) save the table. First an error message appears (although I don't understand the reason)
![Clipboard02](https://user-images.githubusercontent.com/6983432/58765664-7ad5a380-8575-11e9-90ad-2ffc3093c39d.jpg)

3. Finally the message disappears but the work in progress symbol stays until the EOD 
![Clipboard03](https://user-images.githubusercontent.com/6983432/58765688-cee08800-8575-11e9-8f8b-addd2e869ee0.jpg)

**Comment by bennothommo** [comment] 2019-06-02 23:52
@ovillani Thanks for the info. We will investigate the hang after the error message is shown. As for the error itself, that is a legitimate error. You have two columns marked as primary keys (PK) and have also marked the "id" field as auto-incrementing. This is not possible with MySQL.

**Comment by LukeTowers** [comment] 2019-06-03 02:30
@bennothommo the "hang up" is that the framework.js isn't treating the flash response as a valid request ending response (probably because it might be using the popup handling code which might not have allowances for flash message results). The fix is two fold, make the popup handling JS handle flash responses as valid responses that cancel the loading state and just throw an application exception instead of a flash message here since that's what should actually be happening instead and the popup handling JS handles applicationexceptions in a much better way than a temporary flash message.

**Comment by bennothommo** [comment] 2019-06-09 03:34
@ovillani Would you be able to test the fix applied in https://github.com/octobercms/october/pull/4364 for us? It should hopefully resolve the issue.

**Comment by LukeTowers** [comment] 2019-06-11 14:55
@bennothommo I know https://github.com/octobercms/october/pull/4364 technically fixes this, but could you change the flash message error to a regular ApplicationException instead please? The UI code for handling those is much nicer because it's more readable and it doesn't go away after a short time limit giving the developer enough time to copy the error and google it.

**Comment by bennothommo** [comment] 2019-06-16 05:09
@LukeTowers I've converted the messages to Application Exception messages here: https://github.com/rainlab/builder-plugin/commit/fcb1e052dd305e0a0a969e49441ee14cd55759a9

However, I've noticed today that it has brought back the hanging loading icon with this change. Not sure if it's my local copy or not, but will investigate further.

**Comment by anthonymccourt** [comment] 2019-08-14 14:47
This bug is still present in the latest build. Try marking any non-integer as unsigned to reproduce.

October will recognize the incompatibility but the page will still hang indefinitely with all current modifications to that table lost.
![hang](https://user-images.githubusercontent.com/4533726/63030765-c9bf8380-beaa-11e9-9b8f-539d1666f815.png)

**Comment by LukeTowers** [comment] 2019-08-14 16:31
@bennothommo could you look into this?

**Comment by bennothommo** [comment] 2019-08-15 14:18
@anthonymccourt @LukeTowers Hmmm, I'm not seeing the same here:
![image](https://user-images.githubusercontent.com/15900351/63100892-92380080-bfaa-11e9-8670-9a2d66558216.png)

**Comment by LukeTowers** [comment] 2019-08-15 14:54
@anthonymccourt are you using edge builds?

**Comment by anthonymccourt** [comment] 2019-08-15 15:22
Interesting.
I can reproduce this problem with a fresh install of the latest releases of
October/Builder.

Here's some other info if useful.

October : build 455 (default config) / Builder : v1.0.25
Host : VirtualBox / Centos 7 (PHP v7.3.7) / Apache (v2.4.6) / MariaDB
(v5.5.60)
Native : Win 10 (x64)
Browser : chrome/edge/firefox tested with all extensions disabled


There's also an issue of October reporting an error when attempting to
delete/drop a table from the Builder GUI.
It seems to delete the table successfully and then throw the error that it
can't find the table. See attached screenshot.

Last but not least, I'm having trouble with the Version migrations rollback
feature.
I tested this extensively yesterday and all I can say is that it is
inconsistent. Sometimes it works, sometimes not (for the same version
migration).
I have read that this could be an issue with laravel migration rollbacks in
general. There are posts suggesting you always need to run the
composer dump-autoload  command before a migration rollback. It could be a
caching issue if the problem is inconsistent to reproduce.
All I can tell you is that it appears to happen regularly when the down()
function tries to drop a column.
Yes, I'm one of those weirdos who tests migration down() fucntions...

**Comment by anthonymccourt** [comment] 2019-08-15 15:38
Good spot. I am not.

'edgeUpdates' => false,

**Comment by bennothommo** [comment] 2019-08-15 15:41
@anthonymccourt Thanks for that. In terms of the other issues, would you mind filling out some issues on the [Builder plugin repo](https://github.com/rainlab/builder-plugin/issues/new) and we'll be happy to investigate.

**Comment by anthonymccourt** [comment] 2019-08-15 15:45
I'll do that, no problem.
The edge updates fixes the hanging issue but not the delete table issue.
Should I report the migration rollback issue considering it may not be
related to October?

**Comment by LukeTowers** [comment] 2019-08-15 15:48
Might as well @anthonymccourt

**Comment by bennothommo** [comment] 2019-08-15 15:48
@anthonymccourt Might as well report it - if you can do some testing of that scenario too, that would be super helpful. I've done rollbacks in the Builder plugin before without issue so it could be specific to the migrations you've got.

**Closed by LukeTowers** 2019-08-15 15:48 UTC
Labels: Type: Bug

**Comment by anthonymccourt** [comment] 2019-08-15 16:36
I've submitted the delete table issue. I'll do more testing on the
migrations before submitting anything for that.

The migration rollbacks have always been hit and miss for me so I tend to
only migrate forward and rollback only for testing.

I'm unsure of the merits of the rollback functionality in the first place,
even if only for developing.
I'd rather have an option to take a snapshot of the database schema which
would create the up() methods for it's current state.
Then rolling back the schema would be a nuke and refresh from the snapshot.

The 'updates' folder gets bloated too quickly with migrations for every
little schema tweak, most of which are tweaks and fixes to the initial
schema.

One more thing while I have your ear. Is there any way to prevent builder
from prefixing table names with the plugin and author name?
I have run into problems before with the length of artisan generated
identifier names because my table names are sometimes too long.
Apologies, can of worms here.

**Comment by LukeTowers** [comment] 2019-08-15 22:58
> One more thing while I have your ear. Is there any way to prevent builder
from prefixing table names with the plugin and author name?

@anthonymccourt I don't really want to support no prefix period, it's a standard in October to have all plugin tables prefixed. That would be more of an issue of choosing a shorter author or plugin name and being more succinct in your naming of tables.

**Comment by anthonymccourt** [comment] 2019-08-16 08:33
Okay, good to know.
