### ISSUE TITLE
Date picker's year range is not working

### ISSUE THREAD

**Issue by zooks** [rainlab/builder-plugin#168] opened 2017-08-16 13:13 UTC
And if I set "Min date" and "Max date" which do its job, form input didn't select closest max date. So I need to input it directly.
![october-builder-date-picker-bug](https://user-images.githubusercontent.com/6581623/29364901-b4c50f18-829d-11e7-9581-e2cf7c91f292.png)

**Comment by LukeTowers** [comment] 2017-10-26 21:03
The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.

Closing as it has been over a month since any activity on this occurred.

**Closed by LukeTowers** 2017-10-26 21:03 UTC

**Comment by zooks** [comment] 2017-10-29 01:29
This seems to be a bug, not a question.

**Comment by LukeTowers** [comment] 2017-10-29 01:36
@zooks perhaps it is, however your post was unclear as to what exactly was happening. Could you please describe in detail what is currently happening, what you expect to be happening, and the steps you are taking to reproduce the issue?

And in case you're wondering: 
I'm going crazy with the Abandoned tag in order to prompt some movement with these issues. As it stands right now the core team is way too busy with everything to handle every single issue ourselves.

My solution to this is to poke people into actually taking on the issues that are important to them. If an issue isn't important to them anymore, then they won't do anything and everything will continue as it would have anyways. If it is still important to them, then this will act as a reminder that it still needs to be resolved and hopefully motivate people to try and dig deeper into the issue rather than just assume that the free support of an open source project will solve it for them.

Thanks!
