### ISSUE TITLE
Create new string (localization): Cannot read property 'plugin' of null

### ISSUE THREAD

**Issue by vdomah** [rainlab/builder-plugin#41] opened 2016-02-18 13:41 UTC
When adding a field in fields.yaml in Model section got this error while trying to add new localization string:

Uncaught TypeError: Cannot read property 'plugin' of null
i.onSubmitPopupForm @ build-min.js?v1.0.4:2
n.event.dispatch @ jquery.min.js?v316:3
r.handle @ jquery.min.js?v316:3

https://nimbus.everhelper.me/client/notes/share/399199/wzrb9hxvwtbd6e7ip6cx

**Comment by alekseybobkov** [comment] 2016-02-19 01:22
Hi, 

Is this issue similar to #35 

I can't replicate it. Do you always get it, or only sometimes? What browser and OS you use? Please describe the exact steps for replicating the problem.

**Comment by ardani** [comment] 2016-02-20 15:55
Hi @vdomah that error can solve with start with word "plugin" for localisation
example i want make label for **title** for key i write **plugin.title** then value **title for book**. and save.
you can edit at tab localisation.

**Comment by RectusMedia** [comment] 2016-03-19 16:41
[http://prntscr.com/aha1we](url) [http://prntscr.com/aha3qp](url) for first time it works with **plugin.newkey** in next inputs it broke with same error.
So just try to add one more input with **plugin.key**
p.s. Using latest oCMS version (updated at settings/update)

**Comment by CptMeatball** [comment] 2016-03-19 20:16
+1 for this. Running on local machine (Homestead).

**Comment by alekseybobkov** [comment] 2016-03-20 18:32
Sorry, I still can't replicate it. I don't have access to EL Capitan at the moment. I test in Chrome, FireFox and Safari on an older OSX.

@CptMeatball - can you try Chrome please?

@RectusMedia, @vdomah - what OS and browser you use?

**Comment by jonathannarzo** [comment] 2016-03-24 07:01
same here..
**Error:** Uncaught TypeError: Cannot read property 'plugin' of null
**Browser:** Chrome v49.0.2623.87 m
**OS:** Win 7

**Comment by sorindorobantu** [comment] 2016-03-25 19:45
Same issue

I followed the same steps as @CptMeatball. I tried in Xampp and a production server with Firefox 45.0.1 and Chrome 49.0.2623.87 on Windows 8.1

**Comment by vdomah** [comment] 2016-03-29 09:45
I use Windows 7 with Chrome, Firefox and Vivaldi

**Comment by alekseybobkov** [comment] 2016-03-30 01:43
Still can't reproduce it. I would appreciate if you could help me with resolving it, guys. I see the line in the code where the error is triggered, but I don't see - why. Somebody should link non-minimized versions of the Builder JavaScript files and do some tests.

1 - In plugins/rainLab/builder/controllers/Index.php - replace 
```
$this->addJs('/plugins/rainlab/builder/assets/js/build-min.js', 'RainLab.Builder');
```

with
```
$this->addJs('/plugins/rainlab/builder/assets/js/builder.dataregistry.js', 'RainLab.Builder');
$this->addJs('/plugins/rainlab/builder/assets/js/builder.index.entity.base.js', 'RainLab.Builder');
...
(see the full list of scripts in builder/assets/js/build.js)
```

2 - Make sure that you can reproduce the error.
3 - Put "debugger" to builder.localizationinput.js, in LocalizationInput.prototype.onSubmitPopupForm method:

```
    LocalizationInput.prototype.onSubmitPopupForm = function(ev) {
        var $form = $(ev.target)

        $.oc.stripeLoadIndicator.show()
debugger
        $form.request('onLanguageCreateString', {

```

4 - add a localization string to trigger the error. When the debugger starts, see values if `this`, and `this.options`. They should not be null. Continue the execution to make sure that the error is triggered as expected.
5 - A full call trace of the error would help a lot.

Thanks

**Comment by mashanabja** [comment] 2016-04-07 22:53
Hi alekseybobkov

I am new to this so forgive me if I have done it wrong. Here goes...

I did step 1 of the test process you've suggested :

> 
1 - In plugins/rainLab/builder/controllers/Index.php - replace

$this->addJs('/plugins/rainlab/builder/assets/js/build-min.js', 'RainLab.Builder');
with

$this->addJs('/plugins/rainlab/builder/assets/js/builder.dataregistry.js', 'RainLab.Builder');
$this->addJs('/plugins/rainlab/builder/assets/js/builder.index.entity.base.js', 'RainLab.Builder');
> 

However when I then tried to add a form from model, nothing happens. No output to console either. In fact if tried to do anything on the builder menu, nothing happens and no output to console.

Here's the function inside Index.php after I added the files:

`public function index()
      {
          $this->addCss('/plugins/rainlab/builder/assets/css/builder.css', 'RainLab.Builder');
 
          // The table widget scripts should be preloaded
          $this->addJs('/modules/backend/widgets/table/assets/js/build-min.js', 'core');
          $this->addJs('/plugins/rainlab/builder/assets/js/builder.dataregistry.js', 'RainLab.Builder');
          $this->addJs('/plugins/rainlab/builder/assets/js/builder.index.entity.base.js', 'RainLab.Builder');
  
          $this->pageTitleTemplate = '%s Builder';
      }`

I then reverted the file back to it's original state and then I could add a form and attempted to add a field but again still getting the same error.

Is there something else I can try ?

**Comment by CptMeatball** [comment] 2016-04-07 22:58
Will follow your steps tomorrow!

**Comment by alekseybobkov** [comment] 2016-04-10 18:02
@mashanabja - thanks. I think it doesn't work because you didn't add some JavaScript files in the index() method. See my note in https://github.com/rainlab/builder-plugin/issues/41#issuecomment-203186782:

```
 (see the full list of scripts in builder/assets/js/build.js)
```

This is the full list of scripts to load:

* builder.dataregistry.js
* builder.index.entity.base.js
* builder.index.entity.plugin.js
* builder.index.entity.databasetable.js
* builder.index.entity.model.js
* builder.index.entity.modelform.js
* builder.index.entity.modellist.js
* builder.index.entity.permission.js
* builder.index.entity.menus.js
* builder.index.entity.version.js
* builder.index.entity.localization.js
* builder.index.entity.controller.js
* builder.index.js
* builder.localizationinput.js
* builder.inspector.editor.localization.js
* builder.table.processor.localization.js

Note that `build-min.js` should be __replaced__ with the new scripts.

**Comment by mashanabja** [comment] 2016-04-11 00:49
@alekseybobkov -Thanks

I added the scripts above as suggested, then ran the test

The call stack trace was:
Uncaught TypeError: Cannot read property 'plugin' of null
LocalizationInput.onSubmitPopupForm @ builder.localizationinput.js?v1.0.8:229
n.event.dispatch @ jquery.min.js?v318:3
r.handle @ jquery.min.js?v318:3

Sorry I wasn't quite sure where to look for the following in your instructions: "When the debugger starts, see values if this, and this.options. They should not be null. "

I hope this is helpful. Happy to do more if it could help

**Comment by scosist** [comment] 2016-04-15 14:24
I can confirm this issue, getting the same error:
```
Uncaught TypeError: Cannot read property 'plugin' of null @ build-min.js?v1.0.8:2
    i.onSubmitPopupForm @ build-min.js?v1.0.8:2
    n.event.dispatch @ jquery.min.js?v318:3
    r.handle @ jquery.min.js?v318:3
```

At first, I thought this was a problem with `october:mirror` so tried without but issue remains. Tested on Chromium version 37.0.2062.120 built on Debian 7.6, running on Debian 7.9 (281580) (64-bit).

**Comment by alekseybobkov** [comment] 2016-04-16 18:44
@mashanabja, you need to add the `debugger` command to the script, please see my original instructions in https://github.com/rainlab/builder-plugin/issues/41#issuecomment-203186782. The debugger will stop the script execution and then you can check values of `this` and `this.options` variables. Thanks for the help!

**Comment by mashanabja** [comment] 2016-04-17 00:28
@alekseybobkov . Thanks for your patience. 

I did add the debugger command but just wasn't sure how to proceed from there. Some one gave me a couple of tips.

Steps in chrome developer tools:

1. I then added a breakpoint at line 222 of the localizationinput.js
2. Added debugger command at line 226, below : $.oc.stripeLoadIndicator.show()
    LocalizationInput.prototype.onSubmitPopupForm = function(ev) {
        var $form = $(ev.target)

        $.oc.stripeLoadIndicator.show()
debugger
        $form.request('onLanguageCreateString', {

3. Added a watch expression for this and this.options
4. Added a localization string to trigger the error. When the debugger started, the following values appeared for this, and this.options. 
```
Local
    $form: n.fn.init[1]
    ev: n.Event
    this: LocalizationInput
        disposed: true
        form: null
        initialized: true
        input: null
        newStringPopupMarkup: null
        options: null
        proxiedMethods: null
        > proto__: LocalizationInput
        this.options: null
```
Each time I hit the "step over next function call" button, the above output did not appear to cahnge

When you say you need "A full call trace of the error ", does that mean you need to see the fully expanded list under  > proto__: LocalizationInput or even start stepping into the function or is the above enough?

Hope this is what you were after. Let me know if something else. Attached is a screen shot of my process in case that helps:

![image](https://cloud.githubusercontent.com/assets/4659875/14584366/c492d036-0497-11e6-96d9-c8d87045c5e3.png)

**Comment by alekseybobkov** [comment] 2016-04-17 17:14
Thanks! This helps a lot. `this` variable contents shows that the localization input was disposed too early, which should not happen. I don't understand why it happens and I still can't reproduce the problem, so I have to ask you for more help. Please put `console.trace()` call to the builder.localizationinput.js script, into the dispose() method. It should be around line 30:

```
    LocalizationInput.prototype.dispose = function() {
        console.trace() // I added this call
        this.unregisterHandlers()

       .... 
```

You can also remove the previous `debugger` call from the code. Reload the page, and try to trigger the error again. The console should show the call trace before the error message. Please post the trace information here.

**Comment by mashanabja** [comment] 2016-04-18 11:41
@alekseybobkov 

Ok. Well, it appears to be working now

I did the test as prescribed and got the following output but the field was also created successfully. I then removed the trace and created another field and that was also created successfully.

Below is the details of the output anyway, in case there is something there that helps or perhaps I didn't do it quite right.

Happy to do further testing if needed

```
console.trace()
    LocalizationInput.dispose @ builder.localizationinput.js?v1.0.8:29
    LocalizationEditor.removeLocalizationInput @ builder.inspector.editor.localization.js?v1.0.8:61
    LocalizationEditor.dispose @ builder.inspector.editor.localization.js?v1.0.8:19
    Surface.disposeEditors @ storm-min.js?v318:3566
    Surface.dispose @ storm-min.js?v318:3368
    InspectorContainer.onClose @ storm-min.js?v318:3947
    n.event.dispatch @ jquery.min.js?v318:3
    r.handle @ jquery.min.js?v318:3
```

![image](https://cloud.githubusercontent.com/assets/4659875/14602646/20b80036-05bd-11e6-95fb-e10230bcddfc.png)

**Comment by alekseybobkov** [comment] 2016-04-18 23:42
Please keep the `console.trace()` call in the script until you get the error again. The trace that you posted shows the expected execution flow. We need to catch the trace before the error occurs. Thanks.

**Comment by mashanabja** [comment] 2016-04-19 07:27
Ok, ```console.trace()``` back in but now don't seem to be able to repeat the error. The fields I'm creating appear to be executing correctly with the localisation string included and with out error (see screen shot).

![image](https://cloud.githubusercontent.com/assets/4659875/14630825/375edfec-0664-11e6-905a-9ec835028fe5.png)

**Comment by alekseybobkov** [comment] 2016-04-20 00:08
Just keep `console.trace()` in the code until you get the error. Thanks.

**Comment by dotMastaz** [comment] 2016-05-04 17:11
Hello,

Same error for me...
There are screenshots for Chrome and Firefox
![2016-05-04_19-05-07](https://cloud.githubusercontent.com/assets/1413375/15022440/f7980978-122b-11e6-84b9-da65ee73ec91.jpg)
![2016-05-04_19-02-37](https://cloud.githubusercontent.com/assets/1413375/15022441/f7adcb1e-122b-11e6-8a5c-f6b329e4fb9b.jpg)

**Comment by dotMastaz** [comment] 2016-05-04 23:11
And this is the console.trace before error :
![2016-05-05_01-05-07](https://cloud.githubusercontent.com/assets/1413375/15032123/3e5eae52-125e-11e6-8800-c8e592c78ecc.jpg)

**Comment by dotMastaz** [comment] 2016-05-06 08:53
Help, please !!

**Comment by alekseybobkov** [comment] 2016-05-07 02:47
@mashanabja, @dotMastaz - thanks for the screenshots. Finally we have some information. It looks like the error exists only when the Inspector is displayed as a popover, below the control:

![screen shot 2016-05-06 at 7 41 23 pm](https://cloud.githubusercontent.com/assets/481606/15089845/8e58ec96-13c2-11e6-9d06-fac773e59b9a.png)

When the language string editor popup opens and you click it, the Inspector popover automatically closes
which results in disposing all its editors. 

**As a temporary solution - pin the Inspector with the pin icon in the popover header**

![screen shot 2016-05-06 at 7 43 21 pm](https://cloud.githubusercontent.com/assets/481606/15089849/ced04ef4-13c2-11e6-8a7d-68d5083bd892.png)

When the Inspector is pinned it doesn't close when the localization editor popup opens. At the moment I have no time to fix the popover. Let me know is the temporary solution doesn't work.

**Comment by vdomah** [comment] 2016-05-07 03:26
@alekseybobkov this solution solved the problem, thanks!

**Comment by dotMastaz** [comment] 2016-05-08 22:26
Yes, it's ok too !!
Thank you for your help and for this great plugin !!

**Comment by stadja** [comment] 2016-09-13 10:19
Had the same problem, 
https://github.com/rainlab/builder-plugin/issues/41#issuecomment-217600900 solved it !
Thanks.

**Closed** 2017-01-19 03:08 UTC
Labels: Priority: Low, Status: Accepted, Type: Bug
