### ISSUE TITLE
Builder Plugin issue October 419

### ISSUE THREAD

**Issue by ColdieMoldi** [rainlab/builder-plugin#198] opened 2017-11-06 20:55 UTC
I'm getting `Call to undefined method RainLab\Builder\Widgets\ModelList::getCollapseStatus()` with October on build 419.

I saw another issue which pointed to Builder being updated to work with 420. Is it possible that update broke Builder in version 419?

**Comment by maartenmachiels** [comment] 2017-11-07 09:20
Hi, 

I think @Asinox asked this question just a while ago:
https://github.com/rainlab/builder-plugin/issues/193

Turn on edge updates and the error should disappear. 
Duplicate of #193

**Comment by LukeTowers** [comment] 2017-11-07 14:38
@maartenmachiels is correct. Duplicate of #193

**Closed by LukeTowers** 2017-11-07 14:38 UTC
